# PostgreSQL. Versions 9.1 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  host: postgres          # Point the db to the postgres container(docker)
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: nipishe_development

test:
  <<: *default
  database: nipishe_test

production:
  <<: *default
  database: nipishe_production
  username: nipishe
  password: <%= ENV['NIPISHE_DATABASE_PASSWORD'] %>
